POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Indra Saputra",
    "email": "admin@gmail.com",
    "password": "123123",
    "gender": "L"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "add@gmail.com",
    "password": "123123"
}

###
DELETE http://localhost:5000/logout

###
http://localhost:5000/api/users
Authorization: Bearer 

###
http://localhost:5000/token